# Copyright (c) 2026, eCentric and contributors
"""Document-page Shared-Shell migration contracts (Docs).

Originally GENERATED by ops/migrate_docpages_to_shell.py, DISK-AGGREGATED over
every migrated legacy_pages folder (minus approval_page/all_ticket, owned
elsewhere).

#138 (2026-08-03): the 9 dead legacy_pages folders were removed from the repo
(3 whose live page is now only a ~370-byte redirect stub -- form_po, mso_form,
so_form; 4 deliberately un-published -- client_request, contract_request,
form_rec, vendor_request; 2 whose route is shadowed by a Website Settings
redirect -- gbs_po_form, gbs_so_form). Only the 2 docs pages remain in this
file's scope; all_ticket and approval_page keep their own censuses in
test_legacy_pages_shell.py.

Profiles: form pages require the chainPreview business block; docs pages must
NOT have one. Shared contracts: one shell mount, one header-right slot, zero
static bells, endpoint census locked, zero mojibake."""
import os
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(os.path.dirname(HERE))
LP = os.path.join(APP, "legacy_pages")
PAGES = {'docs_architecture': 'docs', 'docs_gbsflow': 'docs'}          # slug -> profile
ENDPOINTS = {
    "docs_architecture": {},
    "docs_gbsflow": {},
}

# #138: folders removed from the repo. They must NOT come back -- each one would
# reintroduce a page_sync endpoint able to overwrite (and re-publish) a live page.
REMOVED_PAGES = (
    "client_request", "contract_request", "form_po", "form_rec",
    "gbs_po_form", "gbs_so_form", "mso_form", "so_form", "vendor_request",
)


def _read(*p):
    with open(os.path.join(*p), encoding="utf-8") as fh:
        return fh.read()


class TestDocPagesShell(unittest.TestCase):
    def test_shell_zone(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            self.assertEqual(src.count('data-ec-shell="1"'), 1, slug)
            self.assertEqual(src.count('data-ec-shell-header-right="1"'), 1, slug)
            self.assertEqual(src.count('<aside class="ec-sb">'), 0, slug)
            self.assertEqual(src.count('data-ec-notification-bell="1"'), 1, slug)
            self.assertIn('ec-shell-fallback', src, slug)

    def test_profile_contracts(self):
        for slug, profile in PAGES.items():
            src = _read(LP, slug, "main_section.html")
            if profile == "form":
                self.assertIn('<aside id="chainPreview"', src, slug)
            else:
                # docs profile: no chainPreview ELEMENT may be introduced.
                # CSS selectors like `#chainPreview {...}` in legacy shared
                # styles are legitimate and must not fail this contract.
                import re as _re
                self.assertIsNone(
                    _re.search(r'<[a-zA-Z][^>]*\bid="chainPreview"', src), slug)

    def test_endpoint_census(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            for ep, n in ENDPOINTS[slug].items():
                self.assertEqual(src.count("api/method/" + ep), n, "%s:%s" % (slug, ep))

    def test_clean_encoding(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            for mk in ("\u00c3", "\u00c4", "\u00e2\u20ac", "\u00e1\u00bb"):
                self.assertEqual(src.count(mk), 0, "%s:%s" % (slug, mk))

    def test_removed_pages_stay_removed(self):
        """#138: the 9 dead legacy_pages folders must not reappear."""
        for slug in REMOVED_PAGES:
            self.assertFalse(
                os.path.isdir(os.path.join(LP, slug)),
                "legacy_pages/%s was deleted in #138 (dead page: redirect stub, "
                "deliberately un-published, or route shadowed by a redirect). "
                "Re-adding it re-arms a page_sync endpoint that can overwrite and "
                "re-publish the live page." % slug)


if __name__ == "__main__":
    unittest.main()
