# Copyright (c) 2026, eCentric and contributors
"""Document-page Shared-Shell migration contracts (GBS PO/SO + Others + Docs).

GENERATED by ops/migrate_docpages_to_shell.py -- DISK-AGGREGATED over all
migrated legacy_pages (minus approval_page/all_ticket, owned elsewhere).
Profiles: form pages require the chainPreview business block; docs pages must
NOT have one. Shared contracts: one shell mount, one header-right slot, zero
static bells, endpoint census locked, zero mojibake."""
import os
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(os.path.dirname(HERE))
LP = os.path.join(APP, "legacy_pages")
PAGES = {'client_request': 'form', 'contract_request': 'form', 'docs_architecture': 'docs', 'docs_gbsflow': 'docs', 'form_po': 'form', 'form_rec': 'form', 'gbs_po_form': 'form', 'gbs_so_form': 'form', 'mso_form': 'form', 'so_form': 'form', 'vendor_request': 'form'}          # slug -> profile
ENDPOINTS = {
    "client_request": {
        "web_lookup": 7,
        "ecentric_workspace.api.submit_client_request": 1
    },
    "contract_request": {
        "web_lookup": 1,
        "frappe.auth.get_logged_user": 1,
        "submit_contract_request": 1
    },
    "docs_architecture": {},
    "docs_gbsflow": {},
    "form_po": {
        "web_lookup": 4,
        "ec_list_departments": 1,
        "ecentric_workspace.api.submit_po": 1,
        "ecentric_workspace.api.get_so_budget": 1
    },
    "form_rec": {
        "web_lookup": 2,
        "ecentric_workspace.api.submit_rec": 1,
        "ec_list_departments": 1
    },
    "gbs_po_form": {
        "gbs_convert_attachments_to_anon": 2,
        "gbs_create_upload_session": 1,
        "resubmit_gbs_so": 1,
        "ec_get_field_descriptions": 2,
        "gbs_so_create_po_helper": 2,
        "resubmit_gbs_po": 1,
        "gbs_list_po_lookups": 3,
        "web_lookup": 2,
        "submit_gbs_so": 2,
        "submit_gbs_po": 7,
        "gbs_list": 6
    },
    "gbs_so_form": {
        "gbs_convert_attachments_to_anon": 2,
        "gbs_create_upload_session": 1,
        "resubmit_gbs_so": 1,
        "gbs_list_so_lookups": 2,
        "ec_get_field_descriptions": 2,
        "gbs_so_create_po_helper": 1,
        "resubmit_gbs_po": 1,
        "web_lookup": 2,
        "submit_gbs_so": 9,
        "submit_gbs_po": 2,
        "gbs_list": 4,
        "gbs_item_get_uom": 1
    },
    "mso_form": {
        "web_lookup": 1,
        "ec_list_departments": 1,
        "ec_create_upload_session": 1,
        "submit_mso_v2": 2
    },
    "so_form": {
        "ec_create_upload_session": 1,
        "submit_so_v2": 2,
        "ec_list_departments": 1,
        "ecentric_workspace.api.get_mso_budget": 1,
        "web_lookup": 1
    },
    "vendor_request": {
        "web_lookup": 7,
        "ecentric_workspace.api.submit_vendor_request": 1
    }
}


def _read(*p):
    with open(os.path.join(*p), encoding="utf-8") as fh:
        return fh.read()


class TestDocPagesShell(unittest.TestCase):
    def test_shell_zone(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            self.assertEqual(src.count('data-ec-shell="1"'), 1, slug)
            self.assertEqual(src.count('data-ec-shell-header-right="1"'), 1, slug)
            self.assertEqual(src.count('<aside class="ec-sb">'), 0, slug)
            self.assertEqual(src.count("data-ec-notification-bell"), 0, slug)
            self.assertIn('class="ec-shell-fallback"', src, slug)

    def test_profile_contracts(self):
        for slug, profile in PAGES.items():
            src = _read(LP, slug, "main_section.html")
            if profile == "form":
                self.assertIn('<aside id="chainPreview"', src, slug)
            else:
                # docs profile: no chainPreview ELEMENT may be introduced.
                # CSS selectors like `#chainPreview {...}` in legacy shared
                # styles are legitimate and must not fail this contract.
                import re as _re
                self.assertIsNone(
                    _re.search(r'<[a-zA-Z][^>]*\bid="chainPreview"', src), slug)

    def test_endpoint_census(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            for ep, n in ENDPOINTS[slug].items():
                self.assertEqual(src.count("api/method/" + ep), n, "%s:%s" % (slug, ep))

    def test_clean_encoding(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            for mk in ("\u00c3", "\u00c4", "\u00e2\u20ac", "\u00e1\u00bb"):
                self.assertEqual(src.count(mk), 0, "%s:%s" % (slug, mk))


if __name__ == "__main__":
    unittest.main()
