# Copyright (c) 2026, eCentric and contributors
"""Document-page Shared-Shell migration contracts (GBS PO/SO + Others).

Generated by ops/migrate_docpages_to_shell.py. Zone law: only the embedded
sidebar + bell are shell chrome; everything else (chainPreview, all endpoints)
is the untouched business zone. Endpoint census locks every action path."""
import os
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(os.path.dirname(HERE))
LP = os.path.join(APP, "legacy_pages")
PAGES = ('gbs_po_form', 'gbs_so_form')
ENDPOINTS = {
    "gbs_po_form": {
        "gbs_list_po_lookups": 3,
        "web_lookup": 2,
        "gbs_so_create_po_helper": 2,
        "gbs_list": 6,
        "submit_gbs_po": 7,
        "ec_get_field_descriptions": 2,
        "resubmit_gbs_po": 1,
        "gbs_convert_attachments_to_anon": 2,
        "gbs_create_upload_session": 1,
        "submit_gbs_so": 2,
        "resubmit_gbs_so": 1
    },
    "gbs_so_form": {
        "gbs_item_get_uom": 1,
        "web_lookup": 2,
        "gbs_list_so_lookups": 2,
        "gbs_so_create_po_helper": 1,
        "gbs_list": 4,
        "ec_get_field_descriptions": 2,
        "submit_gbs_po": 2,
        "resubmit_gbs_po": 1,
        "gbs_convert_attachments_to_anon": 2,
        "gbs_create_upload_session": 1,
        "submit_gbs_so": 9,
        "resubmit_gbs_so": 1
    }
}


def _read(*p):
    with open(os.path.join(*p), encoding="utf-8") as fh:
        return fh.read()


class TestDocPagesShell(unittest.TestCase):
    def test_shell_zone(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            self.assertEqual(src.count('data-ec-shell="1"'), 1, slug)
            self.assertEqual(src.count('data-ec-shell-header-right="1"'), 1, slug)
            self.assertEqual(src.count('<aside class="ec-sb">'), 0, slug)
            self.assertEqual(src.count("data-ec-notification-bell"), 0, slug)
            self.assertIn('class="ec-shell-fallback"', src)

    def test_business_contracts(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            self.assertIn('<aside id="chainPreview"', src, slug)
            for ep, n in ENDPOINTS[slug].items():
                self.assertEqual(src.count("api/method/" + ep), n, "%s:%s" % (slug, ep))

    def test_clean_encoding(self):
        for slug in PAGES:
            src = _read(LP, slug, "main_section.html")
            for mk in ("\u00c3", "\u00c4", "\u00e2\u20ac", "\u00e1\u00bb"):
                self.assertEqual(src.count(mk), 0, "%s:%s" % (slug, mk))


if __name__ == "__main__":
    unittest.main()
